export class TsiParserConfigNames {

    public static  PARSER_CONFIG_CONF = "CONFPRSCFG";
    public static  PARSER_CONFIG_SYNCFILE = "SYNCFILEPRSCFG";
    public static  PARSER_CONFIG_CATEGORY = "CATEGORYPRSCFG";
    public static  PARSER_CONFIG_ARTICLE = "ARTICLEPRSCFG";
    public static  PARSER_CONFIG_CUSTOMER = "CUSTOMERPRSCFG";
    public static  PARSER_CONFIG_CUSTOMER_CATALOG = "CUSTOMERCATALOGPRSCFG";
    public static  PARSER_CONFIG_ORDER = "ORDERPRSCFG";
    public static  PARSER_CONFIG_SHOPPING_CART_ORDERS = "CARTORDERSPRSCFG";
    public static  PARSER_CONFIG_SHOPPING_CART_DATA = "CARTDATAPRSCFG";
    public static  PARSER_CONFIG_EXPENDITURES = "EXPENDITURESPRSCFG";
    public static  PARSER_CONFIG_EXPENDITURE_SUGGESTIONS = "EXPENDITURESUGGESTIONPRSCFG";
    public static  PARSER_CONFIG_LICENCE_NUMBER = "LICENCENUMBERPRSCFG";
    public static  PARSER_CONFIG_LICENCE_NUMBER_SUGGESTIONS = "LICENCENUMBERSUGGESTIONPRSCFG";
    
    public static  PARSER_CONFIG_EXPANDITURES_EMAIL = "EXPANDITURESEMAILPRSCFG";
    public static  PARSER_CONFIG_KM_EMAIL = "KMEMAILPRSCFG";
    public static  PARSER_CONFIG_CATALOG_TAB_HEADERS = "CATALOGTABHEADERS";
    public static  PARSER_CONFIG_NEW_CUSTOMER_CONF = "NEWCUSTOMERCONF";
}